import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { ToastInjection } from "@/lib/toast";
import { ThemeProvider } from "@/providers/theme-provider";

const nunito = Nunito({
  subsets: ["cyrillic"],
  variable: "--font-nunito",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Iron Track App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${nunito.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="mx-auto max-w-screen-md h-screen flex flex-col">
            <main className="flex-grow">{children}</main>
          </div>
          <ToastInjection />
        </ThemeProvider>
      </body>
    </html>
  );
}
